apiVersion: v1
kind: Service
metadata:
  name: historyserver
  namespace: default
spec:
  ports:
  - name: web
    port: 19888
    nodePort: 31888 
  type: NodePort
  selector:
    app: historyserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: historyserver
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: historyserver
  template:
    metadata:
      labels:
        app: historyserver
    spec:
      imagePullSecrets:
      - name: {{ .Values.global.imagePullSecret }}
      containers:
      - name: historyserver
        image: "{{ .Values.global.registry }}/hadoop-historyserver:latest"
        env:
        - name: HADOOP_OPTS
          value: "-Dyarn.timeline-service.store-class=org.apache.hadoop.yarn.server.timeline.FileSystemTimelineStore -Dyarn.timeline-service.fs-timeline-store.path=/yarn/timeline"
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-hadoop-env
        ports:
        - containerPort: 19888

