apiVersion: v1
kind: Service
metadata:
  name: namenode 
  namespace: default
spec:
  clusterIP: None 
  ports:
  - name: fs
    port: 9000
  - name: web
    port: 9870
  selector:
    app: namenode
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: namenode
spec:
  serviceName: "namenode"
  replicas: {{ .Values.namenode.replicaCount }}
  template:
    metadata:
      labels:
        app: namenode
   template:
    spec:
      containers:
        - name: datanode
          volumeMounts:
            - name: datanode-storage
              mountPath: /hadoop/dfs/data
  volumeClaimTemplates:           # <-- creates one PVC per replica automatically
    - metadata:
        name: datanode-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path   # your k3s storage class
        resources:
          requests:
            storage: 20Gi