apiVersion: v1
kind: Service
metadata:
  name: namenode 
  namespace: default
spec:
  clusterIP: None 
  ports:
  - name: fs
    port: 9000
  - name: web
    port: 9870
  selector:
    app: namenode
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: namenode
spec:
  serviceName: "namenode"
  replicas: {{ .Values.namenode.replicaCount }}
  selector:
    matchLabels:
      app: namenode
  template:
    metadata:
      labels:
        app: namenode
    spec:
      nodeSelector:
        {{ .Values.nodeRoles.masterKey }}: {{ .Values.nodeRoles.masterValue | quote }}
      imagePullSecrets:
      - name: {{ .Values.global.imagePullSecret }}
      containers:
      - name: namenode
        image: "{{ .Values.global.registry }}/hadoop-namenode:latest"
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-hadoop-env
        volumeMounts:
        - name: namenode-storage
          mountPath: /hadoop/dfs/name
      volumes:
      - name: namenode-storage
        hostPath:
          path: {{ .Values.namenode.hostPath }}
