apiVersion: v1
kind: Service
metadata:
  name: hadoop-workers-dns
  namespace: default
spec:
  clusterIP: None
  selector:
    app: worker
  ports:
  - name: dummy
    port: 9999
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hadoop-workers
  namespace: default
spec:
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      subdomain: "hadoop-workers-dns" 
      imagePullSecrets:
      - name: {{ .Values.global.imagePullSecret }}
      containers:
      - name: datanode
        image: "{{ .Values.global.registry }}/hadoop-datanode:latest"
        env:
        - name: HADOOP_OPTS
          value: "-Ddfs.datanode.hostname=$(MY_POD_NAME).hadoop-workers-dns.default.svc.cluster.local"
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-hadoop-env

        volumeMounts:
        - name: hdfs-data
          mountPath: /hadoop/dfs/data
      - name: nodemanager
        image: "{{ .Values.global.registry }}/hadoop-nodemanager:latest"
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-hadoop-env
      volumes:
      - name: hdfs-data
        hostPath:
          path: {{ .Values.workers.hostPath }}
          type: DirectoryOrCreate
