global:
  registry: ghcr.io/gabjea
  imagePullSecret: ghcr-secret

hadoopEnv:
  fsDefaultFS: "hdfs://namenode:9000"
  resourcemanagerHostname: "resourcemanager"
  multihomedNetwork: "1"
  clusterName: "hadoop-team-cluster"
  jobhistoryAddress: "historyserver:10020"
  jobhistoryWebappAddress: "historyserver:19888"
  JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-universal/"


nodeRoles:
  masterKey: "node-role.kubernetes.io/master"
  masterValue: "true"
  workerKey: "hadoop-role"
  workerValue: "worker"

namenode:
  replicaCount: 1
  hostPath: "/data/hadoop/name"

workers:
  hostPath: "/data/hadoop/data"
